describe('Burger Builder test', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('Visits the Burger builder home page', () => {
    cy.contains('Burger Builder')
    cy.contains('Login')
  })
})
describe('Login test', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('Visits the login page', () => {
    cy.contains('Login').click()
    cy.contains('Signin')
    cy.contains('Signin').click()
    cy.contains('Register')
    cy.contains('Register').click()
    cy.get('input[placeholder="E-mail Address"]').type('john-doe@example.com')
    cy.get('input[placeholder="Password"]').type('password')
    cy.get('button[type="submit"]').should('be.visible').click()
    cy.url().should('eq', 'http://localhost:3000/')
    cy.contains('Orders')
  })
})
describe('Create order test', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('Creates order for a burger', () => {
    cy.contains('Lettuce')
    cy.contains('Bacon')
    cy.contains('Cheese')
    cy.contains('Meat')
    cy.contains('SIGN UP TO ORDER').should('be.disabled')
    cy.get('.Less').should('be.disabled')
    cy.get('.More').should('not.be.disabled')
    cy.get('.More').click({ multiple: true })
    cy.get('.Less').should('not.be.disabled')
    cy.contains('SIGN UP TO ORDER').should('not.be.disabled').click()
    cy.url().should('eq', 'http://localhost:3000/login')
  })
})
describe('Orders test', () => {
  beforeEach(() => {
    cy.visit('/')
    cy.contains('Login').click()
    cy.get('input[placeholder="E-mail Address"]').type('john-doe@example.com')
    cy.get('input[placeholder="Password"]').type('password')
    cy.get('button[type="submit"]').should('be.visible').click()
  })
  it('Orders burger successfully', () => {
    cy.contains('ORDER NOW').should('be.disabled')
    cy.get('.More').click({ multiple: true })
    cy.contains('ORDER NOW').should('not.be.disabled').click()
    cy.contains('CONTINUE').should('be.visible').click()
    cy.contains('We hope it tastes well!').should('be.visible')
    cy.contains('Continue').should('be.visible').click()
    cy.contains('Enter your Contact Data').should('be.visible')
    cy.get('input[placeholder="Your Name"]').type('Usama')
    cy.get('input[placeholder="Street"]').type('14')
    cy.get('input[placeholder="Zip Code"]').type('49600')
    cy.get('input[placeholder="Country"]').type('Pakistan')
    cy.get('input[placeholder="E-mail"]').type('john-doe@example')
    cy.contains('ORDER').should('be.disabled')
    cy.get('input[placeholder="E-mail"]').type('.com')
    cy.contains('ORDER').should('not.be.disabled').click()
  })
})
